- name: variables from PLAY level
  hosts: localhost
  vars: 
    Course: "Devops"
    Trainer: "Sunil"
    Duration: "110HRS"
  tasks:
  - name: check variables
    ansible.builtin.dedug:
     msg: "Hi, I am learnimg {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}""