- name: variables from PLAY level
  hosts: localhost
  vars_files:
  - variables.yaml
  # vars_prompt:
  # - name: PERSON
  #   prompt: Please enter your name
  #   private: false # user can see what thet are entering
  # - name: WISHES
  #   prompt: Please enter your wishes
  #   private: false # user can't see what are entering
  vars:
   PERSON: "sunil from play"
   WISHES: "Morning from play"
  tasks:
  - name: check variables
    # vars:
    #   PERSON: "sunil from Task"
    #   WISHES: "Morning from Task"
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good  {{WISHES}}"



  # preferences
  #1 CMD
  #2 task
  #3 files
  #4 prompt